-- Excess Baggage Report - Supabase setup
-- Run this entire script in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  user_code text not null unique,
  role text not null default 'user' check (role in ('user','supervisor')),
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  emd_number text not null,
  issue_date text,
  sign_in text,
  report_data jsonb not null,
  created_at timestamptz not null default now(),
  unique(user_id, emd_number)
);

create index if not exists reports_user_id_idx on public.reports(user_id);
create index if not exists reports_emd_number_idx on public.reports(emd_number);
create index if not exists reports_issue_date_idx on public.reports(issue_date);

alter table public.profiles enable row level security;
alter table public.reports enable row level security;

create or replace function public.is_supervisor()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'supervisor'
  );
$$;

grant execute on function public.is_supervisor() to authenticated;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_supervisor());

drop policy if exists "reports_select_own_or_supervisor" on public.reports;
create policy "reports_select_own_or_supervisor"
on public.reports for select
to authenticated
using (user_id = auth.uid() or public.is_supervisor());

drop policy if exists "reports_insert_own" on public.reports;
create policy "reports_insert_own"
on public.reports for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "reports_update_own" on public.reports;
create policy "reports_update_own"
on public.reports for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "reports_delete_own_or_supervisor" on public.reports;
create policy "reports_delete_own_or_supervisor"
on public.reports for delete
to authenticated
using (user_id = auth.uid() or public.is_supervisor());

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, user_code, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'user_code', split_part(new.email,'@',1)), 'user')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- IMPORTANT:
-- 1. Create your own account from the website first.
-- 2. Then replace YOUR_USER_ID below with the generated profile id
--    OR identify the profile using the user_code, and run:
--
-- update public.profiles
-- set role='supervisor'
-- where user_code='YOUR_SUPERVISOR_USER_ID';
--
-- Example:
-- update public.profiles set role='supervisor' where user_code='37888';

-- The website uses ID/password accounts by mapping the User ID to
-- a synthetic internal email such as 37888@excessbaggage.local.
-- For this design, turn OFF email confirmation in Supabase Auth settings.
